version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/lib"
      - "/examples/*"
      - "/profile_target/*"      
    schedule:
      interval: "weekly"
