[workspace]
members = [
  "./lib",
  "./examples/globe/canvas",
  "./examples/globe/rotating_wgpu",
  "./examples/globe/rotating_50m",
  "./examples/globe/drag_and_zoom",
  "./examples/globe/svg",
  "./examples/globe/albers_usa_svg",
  "./examples/projections",
  "./examples/ring",
  "./examples/multi_threaded",
  "./profile_target/albers_svg",
  './profile_target/simple_svg',
]
resolver = "2"
default-members = ["./lib"]

[workspace.package]
authors = ["martin <martinfrances107@hotmail.com>"]
categories = ["graphics", "Mathematics"]
edition = "2021"
keywords = ["diagram", "graphics"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/martinfrances107/rust_d3_geo"
version = "3.2.4"

# Version 1.65 is required as this package makes use of "Generic Associated Types".
# Version 1.80 LazyLock is stabilized in 1.80
# ( Side note:  LazyLock is used **ONLY** in benchmarking, it is set here to support dev builds.
# The underlying library is 1.65 )
rust-version = "1.80"

[workspace.dependencies]
d3_geo_rs = { path = "../../lib" }
# Design instability
# geo 0.31 needs updating but a problem need fixing see the definition of getrandom
geo = "0.33.0"
geo-types = "0.7.17"
# Create a shadow dependency on getrandom with the feature "js"
# In effect this will add the "js" feature flag to the real depedency
# d3_geo_rs -> geo -> rand -> genrandom
# The design instability is the version of get random here must be kept in sync with the verison
# used in the geo crate.
getrandom = { version = "0.4.3", features = ["wasm_js"] }
gloo-utils = "~0.3"
js-sys = "~0.3"
serde_json = "~1"
futures = "~0.3"
rand = { version = "~0.10" }
rust_topojson_client = { git = "https://github.com/martinfrances107/rust_topojson_client.git", branch = "main" }
topojson = "~0.5"
wasm-bindgen = "~0.2"
wasm-bindgen-test = "~0.3"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"
wgpu = "30.0"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.dev]
debug = true
