pub mod azimuthal;
pub mod azimuthal_equal_area;
pub mod center;
pub mod clip_extent;
pub mod equirectangular;
pub mod gnomic;
pub mod mecator;
pub mod orthographic;
pub mod projection;
pub mod projection_equal;
pub mod projection_trait;
pub mod resample;
pub mod scale;
pub mod scale_translate;
pub mod scale_translate_rotate;
pub mod stereographic;
pub mod stream_transform;
pub mod stream_transform_radians;
pub mod translate;

mod fit;
