[package]
authors = { workspace = true }
categories = { workspace = true }
description = "A example app from the rust_d3_geo package. It shows how rust can interact with the browsers timer API."
edition = { workspace = true }
# license = { workspace = true }
keywords = { workspace = true }
license = "MIT"
name = "rust_d3_geo_example_globe_rotating_50m"
readme = { workspace = true }
repository = "https://github.com/martinfrances107/rust_d3_geo_voronoi.git"
version = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = { workspace = true }
geo = { workspace = true }
geo-types = { workspace = true }
gloo-utils = { workspace = true }
gloo-timers = { version = "~0.2", features = ["futures"] }
futures = "~0.3"
rust_d3_geo = { path = "../../../lib" }
rust_topojson_client = { workspace = true }
topojson = { workspace = true }
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
wasm-bindgen-test = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "Attr",
    "console",
    "CanvasRenderingContext2d",
    "Document",
    "Element",
    "Event",
    "Headers",
    "EventTarget",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "Node",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Text",
    "Window",
]
