[package]
name = "rust_d3_geo_benchmark_svg"
description="rust_d3_geo benchmark wasm app"
license = "MIT"
version = "0.1.0"
authors = ["martin <martinfrances107@hotmail.com>"]
edition = "2018"
[lib]
crate-type = ["cdylib"]


[features]
# If you uncomment this line, it will enable `wee_alloc`:
#default = ["wee_alloc"]

[dependencies]
js-sys = "0.3.55"
geo={git = "https://github.com/martinfrances107/geo.git", branch="cyclic_match" }
getrandom = { version = "0.2.3", features = ["js"] }
rand = { version = "0.8.4"}
rust_d3_geo = {path="../../lib"}
rust_topojson_client = { git="https://github.com/martinfrances107/rust_topojson_client.git", branch="main"}
serde = { version = "1.0", features = ["derive"] }
topojson = "0.5.0"
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }


# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. However, it is slower than the default
# allocator, so it's not enabled by default.
wee_alloc = { version = "0.4.5", optional = true }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so it's only enabled
# in debug mode.
#[target."cfg(debug_assertions)".dependencies]
#console_error_panic_hook = "0.1.5"


# These crates are used for running unit tests.

futures = "0.3.17"
wasm-bindgen-test = "0.3.28"
wasm-bindgen-futures = "0.4.28"

# The `web-sys` crate allows you to interact with the various browser APIs,
# like the DOM.
[dependencies.web-sys]
version = "0.3.22"
features = [
    "Attr",
    "console",
    "Document",
    "Element",
    "Event",
    "Headers",
    "EventTarget",
    "SvgsvgElement",
    "SvgAnimatedLength",
    "SvgLength",
    "SvgPathElement",
    "HtmlElement",
    "HtmlInputElement",
    "Node",
    "Performance",
    "PerformanceTiming",
    "PerformanceMeasure",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Text",
    "Window"
]
