name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features

  # Check formatting with rustfmt
  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      # Removed as I as exceeding the allowed time on github.
      # - name: Run cargo-tarpaulin
      #   uses: actions-rs/tarpaulin@v0.1
      #   with:
      #     version: '0.15.0'
      #     args: '--workspace --out Xml -- --test-threads 1'
      # - name: Upload to codecov.io
      #   uses: codecov/codecov-action@v3
      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: code-coverage-report
      #     path: cobertura.xml
